# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"]\n\x10InferenceRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x11\n\ttenant_id\x18\x04 \x01(\t\"h\n\x11InferenceResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\x05\x12\x12\n\nlatency_ms\x18\x03 \x01(\x02\x12\x12\n\nrequest_id\x18\x04 \x01(\t2\xa2\x01\n\x10InferenceService\x12\x42\n\x05Infer\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponse\x12J\n\x0bInferStream\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=30
  _globals['_INFERENCEREQUEST']._serialized_end=123
  _globals['_INFERENCERESPONSE']._serialized_start=125
  _globals['_INFERENCERESPONSE']._serialized_end=229
  _globals['_INFERENCESERVICE']._serialized_start=232
  _globals['_INFERENCESERVICE']._serialized_end=394
# @@protoc_insertion_point(module_scope)
