"""add inference_log table

Revision ID: 12761ad0629c
Revises: 3a5de8e91084
Create Date: 2026-04-05 16:24:30.659365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12761ad0629c'
down_revision: Union[str, Sequence[str], None] = '3a5de8e91084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('protocol', sa.Enum('http', 'ws', 'grpc', name='protocolenum'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'error', 'timeout', name='statusenum'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_logs_created_at'), 'inference_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_logs_id'), 'inference_logs', ['id'], unique=False)
    op.create_index(op.f('ix_inference_logs_model_name'), 'inference_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_inference_logs_status'), 'inference_logs', ['status'], unique=False)
    op.create_index(op.f('ix_inference_logs_tenant_id'), 'inference_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_logs_tenant_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_status'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_model_name'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_id'), table_name='inference_logs')
    op.drop_index(op.f('ix_inference_logs_created_at'), table_name='inference_logs')
    op.drop_table('inference_logs')
    # ### end Alembic commands ###
